---
title: "trabajo 3 estadistica inferencia"
author: "Nicolas salinas"
date: "2024-04-02"
output: html_document
---

## PREGUNTA 1

### Si la ingeniera está seguro de que el verdadero volumen medio no puede ser superior a 10 litros y piensa rechazar la hipótesis nula cuando la muestra presente una media menor a 9,8 litros, ¿cuál es la probabilidad de que cometa un error de tipo I? Para responder, generen un gráfico de la distribución muestral de las medias hipotetizada en donde se marque la zona correspondiente a la probabilidad solicitada, para luego, basándose en este gráfico, calcular el área correspondiente. Tome como ejemplo los scripts presentados en la lectura sobre poder estadístico. 

Media de población μ \< 10


## Pregunta 2
### Si el verdadero volumen medio de los bidones fuera de 9,85 litros, ¿cuál sería la probabilidad de que la ingeniera, que obviamente no conoce este dato, cometa un error de tipo II? Para responder, agregue al gráfico anterior la verdadera distribución muestral de las medias y marquen (con otro color) la zona correspondiente a la probabilidad solicitada, para luego, basándose en este gráfico, calcular el área correspondiente. También hay ejemplos de este procedimiento en la lectura sobre poder estadístico.

```{r}
library(ggplot2)
library(ggpubr)
library(ggpattern)

alfa <- 0.05
n <- 100

media_nula <- 10
sigma <- 1

error <- sigma/sqrt(n)

g_xlimites <- media_nula + c(-6,5) * error

g <- ggplot() + xlim(g_xlimites)
g<- g+ labs(x = "cantidad de detergente en los bidones", y = "densidad")
g <- g + labs(title = "distribucion de las medias de los bidones de detergete")
g <- g + theme_pubr()

dist_0 <- stat_function(fun = dnorm,
                        args =list(mean = media_nula, sd = error),
                        geom = "area",
                        colour = "red", fill = "red", alpha = 0.1)

g1 <- g + dist_0
g1 <- g1 + geom_vline(xintercept = media_nula, colour = "red")

z_inferior <- qnorm(alfa/2, mean = media_nula, sd = error, lower.tail = TRUE)
z_superior <- qnorm(alfa/2, mean = media_nula, sd = error, lower.tail = FALSE)

g2 <- g1 + stat_function(fun = dnorm,
                         args = list(mean = media_nula,
                                     sd = error)
                         geom = "area",
                         xlim = c(g_xlimites[1], z_inferior),
                         fill = "red", alpha = 0.6)
g2 <- g2 + stat_function(fun = dnorm,
                         args = list(mean = media_nula, sd = error),
                         geom = "area",
                         xlim = c(z_superior, g_xlimites[2]),
                         fill = "red", alpha = 0.6)

print(g2)

#Valores reales
media_verdadera <- 9.85
delta <- media_nula - media_verdadera

dist_v <- stat_function(fun = dnorm,
                         args = list(mean = media_verdadera,
                                     sd = error)
                         geom = "area",
                         colour = "blue", fill = "blue", alpha = 0.1)

g3 <- g2 + dist_v + geom_vline(xintercept = media_verdadera, colour = "blue")

x_ann <- c(media_verdadera, media_nula)
y_ann <- c(dnorm(media_verdadera, mean = media_verdadera, sd = error),
           dnorm(media_nula, mean = media_nula, sd = error))
y_ann <- y_ann + 0.01

g3 <- g3 + annotate("segment", x = x_ann[1], y = y_ann[1],
                    xend = x_ann[2], yend = y_ann[2],
                    arrow = arrow(angle = 10, length = unit(0.03, "npc"),
                                  ends = "both", type = "open"))

g3 <- g3 + annotate("text", x = sum(x_ann)/2, y = y_ann[1] - 0.001,
                    label = "delta", vjust = "top", parse = TRUE)
print(g3)


g4 <- g+ dist_0 + dist_v
g4<- g4 + stat_function(fun = dnorm,
                        args = list(mean = media_verdadera, sd = error),
                        geom = "area",
                        xlim = c(g_xlimites[1], z_inferior),
                        fill = "blue", alpha = 0.6)

g4<- g4 + stat_function(fun = dnorm,
                        args = list(mean = media_verdadera, sd = error),
                        geom = "area",
                        xlim = c(z_superior, g_xlimites[2]),
                        fill = "blue", alpha = 0.6)

g4<- g4 + stat_function(fun = dnorm,
                        args = list(mean = media_verdadera, sd = error),
                        geom = "area_pattern",
                        xlim = c(z_inferior, z_superior),
                        fill = "white", colour = "blue", alpha = 0.3,
                        pattern_spacing = 0.15, pattern_density = 0.4,
                        pattern_fill = "blue", pattern_colour = "blue",
                        pattern_angle = 45, pattern_alpha = 0.3)

print(g4)

#calcular probabildad de cometer un error tipo 2

poder_inf <- pnorm(z_inferior, mean = media_verdadera, sd = error, lower.tail = TRUE)
poder_sup <- pnorm(z_superior, mean = media_verdadera, sd = error, lower.tail = FALSE)

poder <- poder_inf + poder_sup

beta <- 1- poder
cat("error tipo 2", beta)
```



## Pregunta 3 
### Como no se conoce el verdadero volumen medio, genere un gráfico del poder estadístico con las condiciones anteriores, pero suponiendo que el verdadero volumen medio podría variar de 9,5 a 10 litros. Hay un ejemplo de este tipo de gráfico en la lectura sobre poder estadístico.


## Pregunta 4
### Considerando un volumen medio de 10 litros, ¿cuántos bidones deberían revisarse para conseguir un poder estadístico de 0,75 y un nivel de significación de 0,05?

## Pregunta 5
### ¿Alcanzaría esta muestra para detectar la diferencia que la ingeniera sospecha que existe entre las dos máquinas de la planta con las mismas probabilidades de cometer errores?